# Generated by Django 4.2 on 2025-06-22 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Meeting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='عنوان الاجتماع')),
                ('audio_file', models.FileField(upload_to='audio/', verbose_name='الملف الصوتي')),
                ('transcript', models.TextField(blank=True, null=True, verbose_name='النص المحول')),
                ('summary', models.TextField(blank=True, null=True, verbose_name='التلخيص')),
                ('minutes', models.TextField(blank=True, null=True, verbose_name='محضر الاجتماع')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'اجتماع',
                'verbose_name_plural': 'الاجتماعات',
                'ordering': ['-created_at'],
            },
        ),
    ]
